### ISSUE TITLE
Quality of Life Updates

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#29]
This issue will be used for tracking any Quality of Life update/Improvement. An issue should be created for each task referencing back to this issue. (`Example: #30`)
# Task
- [x] Update README to show examples of the prerequisites API keys needed for working with Backend. Create a `.env.example` in to config folder. #30 
- [x] Add a new scripts to `package.json` to reduce the amount of commands needed to run for getting started with the project. Add instructions to readme.
- [ ] Considering adding a skeleton page structure for routing e.g. Landing page, Calendar page so that other collbarator can focus on building out said pages without having to worry about needing to setup React core routing functionalities.
- [x] Possibly add Eslint & Prettier to auto format code to keep consistency throughout codebase?
- [x] Remove views folder which contains all the EJS files now that the Frontend is build in React.
- [x] Remove Procfile.

Hey @Caleb-Cohen, do you approve of these Quality of Life update to the project? Is there anything that should be added or remove from the tasks?

**Comment by Caleb-Cohen** [comment]
I added it to the project!

**Comment by Caleb-Cohen** [comment]
I added an .ENV example. Can you expand on the first bit regarding examples of API keys?

**Comment by JoeDravarol** [comment]
> I added an .ENV example. Can you expand on the first bit regarding examples of API keys?

Apologies I did not make it clear. It was to include the Discord API keys: DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET in the README. Which you have updated to reflected that in the *Thing to add* section and also created an `.env.example`. I will mark that task as completed if that's okay?

**Comment by Caleb-Cohen** [comment]
> Apologies I did not make it clear. It was to include the Discord API keys: DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET in the README. Which you have updated to reflected that in the _Thing to add_ section and also created an `.env.example`. I will mark that task as completed if that's okay?

Yes, you can mark it completed. I thought you meant actual examples, but that makes sense. We could probably include the client_ID as that's publicly available. I think we both agree to not make the secret public.

**Comment by JoeDravarol** [comment]
>     * I have no experience with eslint & prettier. Will there be a significant learning curve or is it a plug and play?

I think the difficult part is just setting it up for the project after that, it'll automatically work after npm install. I could be wrong, need to do a bit of research first.

**Comment by JoeDravarol** [comment]
>     * Will the removal of the procfile impact cyclic at all?

Removing the Procfile shouldn't impact Cyclic, I believe it's only used for Heroku.

**Comment by Caleb-Cohen** [comment]
@neoneoexe this is the issue to discuss file cleanup.

**Comment by Caleb-Cohen** [comment]
I want to mention some of these tasks are also in #44. That's ok, just wanted to reference that.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol I've reviewed the bulletproof-react project structure. Seems pretty nice. How does it organize elements that are not currently in the front-end folder? Like controllers?

What other files will be contained in Root other than build, SRC, and Readme.md? 

Additionally, this is going to directly conflict with #46 so we'll need to discuss the best way to move forward.

**Comment by JoeDravarol** [comment]
@Caleb-Cohen The bulletproof-react structure guidleline is only meant for the frontend/client directory anything that is server/backend related will have a it's own organization guidline that we need to agree on.

I have also replied to you at #46 with an example repository on how we should move forward with restructing of the project to make excecuting scripts seamless/easier for new developers.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol Can we close this?

**Comment by JoeDravarol** [comment]
Closing as we are not using React Router.
