### ISSUE TITLE
Tasks Tracker for Re-organize project structure

### ISSUE THREAD

**Issue by JoeDravarol** [Caleb-Cohen/Together#77]
This issue will be used for tracking all the task related to re-organizing the project structure. An issue should be created for each task referencing back to this issue. Example: `This is an issue representing task {x} of issue #77`

We will be using this starter repo as a guideline to re-organize the project structure: https://github.com/fullstack-hy2020/create-app

Note: Task should be started shortly after we do the add-event-form merge, but you can start to familiarize yourself with the formatting required.

- [x] Create a server folder and move anything backend related into said folder. #69
- [x] Combine and relocate all of the package.json, scripts and miscellaneous configuration to the root of the project. #96 
- [x] Improve React project structure using [Bulletproof React](https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md) as guideline. We need to discuss whether we should keep the folder name as **frontend** or change it to **client**. #83
- [x] Refactor/fix the scripts so that it works with new project structure. #103

**Comment by Caleb-Cohen** [comment]
What about adding the remants of #29 to this?

**Comment by JoeDravarol** [comment]
> What about adding the remnants of #29 to this?

I added/moved the tasks related to re-organizing project structure from #29 to this tracker. If this is what you meant? And the tasks that was relocated here is removed from #29

**Comment by Caleb-Cohen** [comment]
@JoeDravarol doesn't #29 also include Skeletal?

**Comment by JoeDravarol** [comment]
> @JoeDravarol doesn't #29 also include Skeletal build out?

That would be more feature based/React specific. That task is building our routing for landing page and calendar page, I don't think we should associate it wtih re-organizing the project structure but we can ask for @MatthewBozin for his input on this.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol It doesn't matter to me if we keep the frontend folder the same or rename it to client. Does anyone have a preference?

**Comment by MatthewBozin** [comment]
@JoeDravarol I think we should keep the react skeleton as it's own thing

@Caleb-Cohen my preference is to rename frontend folder to client

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen my preference is to rename frontend folder to client

Ok, that's what I went with.

**Comment by Caleb-Cohen** [comment]
@JoeDravarol are there any outstanding tasks left here?

**Comment by JoeDravarol** [comment]
Close as completed.
